# Specify sip v6 as the build system for the package.
[build-system]
requires = ["sip >=6, <7"]
build-backend = "sipbuild.api"

[project]
name = "pydmtx-extras"
version = "0.1"
dependencies = ["pydmtx-core"]

[tool.sip.bindings.extras]

[tool.sip.project]
sip-module = "pydmtx.sip"